### ISSUE TITLE
.is-next-container not applied 

### ISSUE THREAD

**Issue by AlexJenter** [swup/parallel-plugin#20]
### What did you expect? 🧐

First Bug report, bare with me and thank you for this great lib!

According to the [parallel-plugin docs](https://swup.js.org/plugins/parallel-plugin/#defining-the-animations) im expecting the documented behaviour. the issue came up at work, somehow the `is-next-container` class is missing.

### What actually happened? 😵‍💫

reduced tha case as far as possible in this [pen](https://codepen.io/AlexJenter/project/editor/ZnpyMA). everything as expected, except for the missing .is-next-container class. i might be missing something so in that case some insight would be highly appreciated.

the `is-next-container` class has a lightcoral background color that is not beeing applied

### Swup and plugin versions 📝

more or less the same in the work project

```html
<script src="https://unpkg.com/swup@4"></script>
<script src="https://unpkg.com/@swup/parallel-plugin@0"></script>
```

### What browsers are you seeing the problem on? 🧭

Firefox, Safari

### URL to minimal reproduction 🔗

https://codepen.io/AlexJenter/project/editor/ZnpyMA

### Checked all these? 📚

- [X] I have read and searched the [official docs](https://swup.js.org)
- [X] I have checked [discussions](https://github.com/orgs/swup/discussions) and [existing issues](https://github.com/issues?q=is:issue+org:swup) for related problems
- [X] I agree to follow this project's [Code of Conduct](https://github.com/swup/.github/blob/master/CODE_OF_CONDUCT.md)
- [X] I have provided all necessary information to the best of my knowledge

**Comment by daun** [comment]
Hi! The class is definitely getting applied, it just doesn't stick around for long. [See this issue for details](https://github.com/swup/parallel-plugin/issues/8). We added [a note in the readme](https://github.com/swup/parallel-plugin?tab=readme-ov-file#defining-the-animations) to clarify things a bit:

> The class `is-next-container` defines the initial state of the next container about to enter the page. As it's only applied for a split second, it won't be visible when inspecting the element in the browser dev tools.

**Comment by daun** [comment]
The question is: do you need the class so stick around? Normal styles can be applied on the container itself, and the `is-next-class` styling only defines the state of it before entering the viewport, i.e. that style probably shouldn't be applied while it's visible.
